export const GETTING_REQUESTS_SUCCESS = 'GETTING_REQUESTS_SUCCESS';
export const GETTING_REQUESTS_ERROR = 'GETTING_REQUESTS_ERROR';

export const CREATE_REQUESTS_SUCCESS = 'CREATE_REQUESTS_SUCCESS';
export const CREATE_REQUESTS_ERROR = 'CREATE_REQUESTS_ERROR';

export const DELETE_REQUESTS_SUCCESS = 'DELETE_REQUESTS_SUCCESS';
export const DELETE_REQUESTS_ERROR = 'DELETE_REQUESTS_ERROR';

export const EDIT_REQUESTS_SUCCESS = 'EDIT_REQUESTS_SUCCESS';
export const EDIT_REQUESTS_ERROR = 'EDIT_REQUESTS_ERROR';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATIONS_ERROR = 'GET_LOCATIONS_ERROR';
